---
title: "CPEAT_manuscript figures - Geo-locations and OC downcore"
author: "Vaasuki Marupaka"
date: 'Summer 2024'
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(googlesheets4)
library(usmap)
library(readr) # read in the csv tables
library(tibble) # use tibbles instead of a data frame
library(plyr) # transform a list into a data frame for the bind
library(dplyr) # work with data tables filters/joins/reframes
library(tidyr) # work with data table pivots
library(ggplot2) # make plots
library(stringr) # extract text from descriptions
library(knitr) # make prettier tables
library(kableExtra) #make tables scrollable
library(pangaear)
knitr::opts_chunk$set(echo = TRUE)
```

# Pull data

## CPEAT

```{r eval=FALSE}

# Check if the folder exists, and create it if it does not
if (!dir.exists("data_lvl1")) {
  dir.create("data_lvl1")
}

if(file.exists('data_lvl1/CPEAT.RData')){
  load('data_lvl1/CPEAT.RData')
}else{
  pages.df <- pg_search("project:label:PAGES_C-PEAT", count = 500) %>% 
    bind_rows(pg_search("project:label:PAGES_C-PEAT", count = 500, offset = 500)) %>% #the output will contain all columns that appear in any of the inputs
    mutate(fullcitation = paste0(citation, ". PANGAEA, https://doi.org/", doi)) #%>% # adds additional column 
  #mutate(fullDOI = paste0("PANGAEA, https://doi.org/", doi))
  
  #Pull into a list, all the data from the files the specified dois in the search results 
  allData.ls <- plyr::dlply(pages.df, #search results
                            c("doi"), #grouping on unique identifer
                            .fun = function(xx) { #defining our fetch function
                              #the pg_data returns a list of a single item, remove that from the parent list
                              return(pg_data(doi = xx$doi, overwrite = FALSE)[[1]])
                            }) 
  
  #long read, save as a formal R data object
  save(pages.df, allData.ls, file = 'data_lvl1/CPEAT.RData')
}

  #Pull the core information by accessing the data item in the lists
  allCores.df <- plyr::ldply(allData.ls, .fun = function(xx) {
    #print(xx$doi)
    if(xx$doi %in% c("10.1594/PANGAEA.934281")){
      names(xx$data)[10] <- 'Age unc [±] (Age, tephra-chronostratigraphy, calculated, 1 sigma)'
    }
    
    if(xx$doi %in% c("10.1594/PANGAEA.934343")){
      names(xx$data)[9] <- 'Age unc [±] (Age, tephra-chronostratigraphy, calculated, 1 sigma)'
    }
    
    if(xx$doi %in% c("10.1594/PANGAEA.941094")){
      names(xx$data)[10] <- 'Age [a AD/CE] alt.'
    }
    
    if(xx$doi %in% c("10.1594/PANGAEA.929068")){
      names(xx$data)[5:7] <- paste(names(xx$data)[5:7], 'alt.') # unknown
    }
    
    if(identical(names(xx$data)[c(2:4, 6:8)], 
                 c("Cal age [ka BP] (Median Age, Age, 14C calibrat...)", 
                   "Cal age max [ka BP] (Age, 14C calibrated, OxCal 4....)",
                   "Cal age min [ka BP] (Age, 14C calibrated, OxCal 4....)",
                   "Cal age [ka BP] (Median Age, Age, 14C calibrat...)",
                   "Cal age max [ka BP] (Age, 14C calibrated, Bacon 2....)",
                   "Cal age min [ka BP] (Age, 14C calibrated, Bacon 2....)")) |
       xx$doi %in% c("10.1594/PANGAEA.929655", "10.1594/PANGAEA.930133")){
      #The method note (OxCal & Bacon) were dropped from the Median Age, so we are adding them back in
      names(xx$data)[c(2:4, 6:8)] <- c(
        'Cal age [ka BP] (Median Age, 14C calibrated, OxCal 4.2.4)', 
        'Cal age max [ka BP] (Age, 14C calibrated, OxCal 4.2.4)', 
        'Cal age min [ka BP] (Age, 14C calibrated, OxCal 4.2.4)',
        'Cal age [ka BP] (Median Age, 14C calibrated, Bacon 2.2)', 
        'Cal age max [ka BP] (Age, 14C calibrated, Bacon 2.2)', 
        'Cal age min [ka BP] (Age, 14C calibrated, Bacon 2.2)') 
    }
    
    if(identical(names(xx$data)[2:7], 
                 c("Cal age [ka BP] (Median Age, Age, 14C calibrat...)", 
                   "Cal age max [ka BP] (Age, 14C calibrated, OxCal 4....)",
                   "Cal age min [ka BP] (Age, 14C calibrated, OxCal 4....)",
                   "Cal age [ka BP] (Median Age, Age, 14C calibrat...)",
                   "Cal age max [ka BP] (Age, 14C calibrated, Bacon 2....)",
                   "Cal age min [ka BP] (Age, 14C calibrated, Bacon 2....)")) |
       xx$doi %in% c("10.1594/PANGAEA.930030")){
      
      names(xx$data)[2:7] <- c(
        'Cal age [ka BP] (Median Age, 14C calibrated, OxCal 4.2.4)', 
        'Cal age max [ka BP] (Age, 14C calibrated, OxCal 4.2.4)', 
        'Cal age min [ka BP] (Age, 14C calibrated, OxCal 4.2.4)',
        'Cal age [ka BP] (Median Age, 14C calibrated, Bacon 2.2)', 
        'Cal age max [ka BP] (Age, 14C calibrated, Bacon 2.2)', 
        'Cal age min [ka BP] (Age, 14C calibrated, Bacon 2.2)') #add the methods that are dropped here
    }
    
    
    if(length(names(xx$data)) > length(unique(names(xx$data)))){
      print(names(xx$data))
    }
    return(mutate(.data = xx$data, across(.cols = everything(),  as.character)))
  }) 
  
  write_csv(allCores.df, file.path('data_lvl1', 'CPEAT_layer.csv'))
  
  #Pull the study information
  allStudy.df <- plyr::ldply(allData.ls, .fun = function(xx) {
    #list out all the possible names for the study info, be sure to update
    #...this list manually if the warning is thrown.
    primaryNames <- intersect(names(xx), c('parent_doi', 'doi', 'citation', 
                                           'url', 'path'))
    
    #There shouldn't be any names that we don't include above.
    if(any( ! (names(xx) %in% c(primaryNames, 'metadata', 'data')))){
      warning(paste('possible missing informatin at primary level for', xx$doi,
                    setdiff(names(xx), c(primaryNames, 'metadata', 'data'))))
    }
    
    #access the study information in the primary list
    ans.ls <- xx[primaryNames]
    
    #deal with the information in the metadata, again we name each possible
    #...list item here and if there are new names this needs to be updated.
    metaNames <- intersect(names(xx$metadata), c("citation", "related_to", "further_details",
                                                 "projects" , "coverage",
                                                 "abstract", "keywords",
                                                 "status",
                                                 "license", "size", "comment"))
    if(any( ! (names(xx$metadata) %in% c(metaNames, 'events', 'parameters')))){
      warning(paste('possible missing informatin at metadata level for', xx$doi))
    }
    
    #append the metadata items to the items from the primary list
    ans.ls <- c(ans.ls, xx$metadata[metaNames])
    
    #Pull in the study information from the 'events' item in the list
    #...again there should be no items that are not matching the manual array here
    eventsNames <- intersect(names(xx$metadata$events), c("LATITUDE", "LONGITUDE",
                                                          "ELEVATION", "ELEVATION START", "ELEVATION END",
                                                          "Penetration", "Recovery",
                                                          "LOCATION", "METHOD/DEVICE", 
                                                          "COMMENT"))
    
    #Take out the first item of the list which is actually the core name itself.
    if(any( ! (names(xx$metadata$events)[-1] %in%  
               c("LATITUDE", "LONGITUDE", "ELEVATION",
                 "ELEVATION START", "ELEVATION END", 
                 "Penetration","Recovery",
                 "LOCATION", "METHOD/DEVICE", "COMMENT")))){
      warning(paste('possible missing informatin at metadata-events level for', xx$doi))
    }
    
    #The core name is a special case where the information is in the name and not
    #...in the list values. Deal with that and append the events information.
    ans.ls <- c(list(core_name = names(xx$metadata$events)[1]),
                ans.ls, 
                xx$metadata$events[eventsNames])
    
    # change everything to a data frame to make it easier to read
    return(as.data.frame(ans.ls, stringsAsFactors = FALSE))
  })
  
  write_csv(allStudy.df, file.path('data_lvl1', 'CPEAT_study.csv'))
  
  #Pull evertyhing else as a parameter
  allParameters.df <-  plyr::ldply(allData.ls, .fun = function(xx) {
    
    ##Copy-paste (sigh... yes I know) from allCores.df construction
    if(xx$doi %in% c("10.1594/PANGAEA.934281")){
      names(xx$data)[10] <- 'Age unc [±] (Age, tephra-chronostratigraphy, calculated, 1 sigma)'
    }
    
    if(xx$doi %in% c("10.1594/PANGAEA.934343")){
      names(xx$data)[9] <- 'Age unc [±] (Age, tephra-chronostratigraphy, calculated, 1 sigma)'
    }
    
    if(xx$doi %in% c("10.1594/PANGAEA.941094")){
      names(xx$data)[10] <- 'Age [a AD/CE] alt.'
    }
    
    if(xx$doi %in% c("10.1594/PANGAEA.929068")){
      names(xx$data)[5:7] <- paste(names(xx$data)[5:7], 'alt.') #true replicates??
    }
    
    if(identical(names(xx$data)[c(2:4, 6:8)], 
                 c("Cal age [ka BP] (Median Age, Age, 14C calibrat...)", 
                   "Cal age max [ka BP] (Age, 14C calibrated, OxCal 4....)",
                   "Cal age min [ka BP] (Age, 14C calibrated, OxCal 4....)",
                   "Cal age [ka BP] (Median Age, Age, 14C calibrat...)",
                   "Cal age max [ka BP] (Age, 14C calibrated, Bacon 2....)",
                   "Cal age min [ka BP] (Age, 14C calibrated, Bacon 2....)")) |
       xx$doi %in% c("10.1594/PANGAEA.929655", "10.1594/PANGAEA.930133")){
      names(xx$data)[c(2:4, 6:8)] <- c(
        'Cal age [ka BP] (Median Age, 14C calibrated, OxCal 4.2.4)', 
        'Cal age max [ka BP] (Age, 14C calibrated, OxCal 4.2.4)', 
        'Cal age min [ka BP] (Age, 14C calibrated, OxCal 4.2.4)',
        'Cal age [ka BP] (Median Age, 14C calibrated, Bacon 2.2)', 
        'Cal age max [ka BP] (Age, 14C calibrated, Bacon 2.2)', 
        'Cal age min [ka BP] (Age, 14C calibrated, Bacon 2.2)') #add the methods that are dropped here
    }
    
    if(identical(names(xx$data)[2:7], 
                 c("Cal age [ka BP] (Median Age, Age, 14C calibrat...)", 
                   "Cal age max [ka BP] (Age, 14C calibrated, OxCal 4....)",
                   "Cal age min [ka BP] (Age, 14C calibrated, OxCal 4....)",
                   "Cal age [ka BP] (Median Age, Age, 14C calibrat...)",
                   "Cal age max [ka BP] (Age, 14C calibrated, Bacon 2....)",
                   "Cal age min [ka BP] (Age, 14C calibrated, Bacon 2....)")) |
       xx$doi %in% c("10.1594/PANGAEA.930030")){
      
      names(xx$data)[2:7] <- c(
        'Cal age [ka BP] (Median Age, 14C calibrated, OxCal 4.2.4)', 
        'Cal age max [ka BP] (Age, 14C calibrated, OxCal 4.2.4)', 
        'Cal age min [ka BP] (Age, 14C calibrated, OxCal 4.2.4)',
        'Cal age [ka BP] (Median Age, 14C calibrated, Bacon 2.2)', 
        'Cal age max [ka BP] (Age, 14C calibrated, Bacon 2.2)', 
        'Cal age min [ka BP] (Age, 14C calibrated, Bacon 2.2)') #add the methods that are dropped here
    }
    
    colHeader <- names(xx$data)
    colDescript <- unlist(lapply(xx$metadata$parameters, paste, collapse = " "))
    
    if(xx$doi == "10.1594/PANGAEA.934274"){
      colDescript <- c(colDescript[1:4], 
                       paste(colDescript[5], ';', colDescript[6]),
                       colDescript[7:9])
    }
    
    #pull the parameter descriptions in and append them to the headers in the data
    ParametersGeo <- data.frame(header = colHeader, 
                                description = colDescript, 
                                stringsAsFactors = FALSE) %>%
      #add in a column index
      mutate(column_index = 1:ncol(xx$data))
    
    return(ParametersGeo)
  })
  
  write_csv(allParameters.df, file.path('data_lvl1', 'CPEAT_parameters.csv'))
  
```

# Bind data together

```{r}
#we are only interested in location-depth, and soil organic carbon variables
#... ignore everything else
CPEAT.df <- read_csv(file = 'data_lvl1/CPEAT_layer.csv', #n_max = 3, 
                     col_types = cols(.default = col_character())) %>%
  select(study_name = doi, 
         contains('Depth sed'),
         #layer_top_m = 'Depth top [m]', layer_bottom_m = 'Depth bot [m]', #all NA
         organic_carbon = 'TOC [%]', carbon = "C [%]", 
         loss_on_ignition = "LOI [%] (weight-%)", 
         bulk_density = "DBD [g/cm**3]", 
         soil_organic_carbon = "Corg dens [g/cm**3]", soil_organic_matter = "OM dens [g/cm**3]" ) %>%
  dplyr::mutate(across(-study_name, as.numeric)) %>%
  #Remote the layers without organic carbon information first so that we can then expand the midpoint definitions
  #filter(is.finite(soil_organic_carbon) | is.finite(soil_organic_matter) | is.finite(bulk_density)) %>%
  dplyr::mutate(soil_orgainc_carbon = case_when(is.finite(soil_organic_carbon) ~ soil_organic_carbon, #39 907 missing
                                         is.finite(bulk_density * organic_carbon) ~ bulk_density * organic_carbon, #38 375 missing
                                         is.finite(soil_organic_matter) ~ soil_organic_matter / 2, #37 776 missing
                                         is.finite(bulk_density * loss_on_ignition) ~ bulk_density * loss_on_ignition / 2, #37 611 missing
                                         is.finite(bulk_density * carbon) ~ bulk_density * carbon, #12 451 missing
                                         TRUE ~ NA)) %>%
  filter(is.finite(soil_organic_carbon)) %>%
  dplyr::mutate(layer_midpoint_m = case_when(is.finite(`Depth sed [m]`) ~ `Depth sed [m]`,
                                      is.finite(`Depth sed [m] (Sample midpoint depth)`) ~ `Depth sed [m] (Sample midpoint depth)`,
                                      is.finite(`Depth sed [m] (LOI sample depth)`) ~ `Depth sed [m] (LOI sample depth)`,
                                      TRUE ~ NA)) %>%
  select(-contains('Depth sed')) %>%
  dplyr::mutate(layer_top_cm = c(0, layer_midpoint_m[1:(n()-1)] + layer_midpoint_m[2:n()])/2 * 100,
         layer_bottom_cm = c((layer_midpoint_m[1:(n()-1)] + layer_midpoint_m[2:n()])/2, layer_midpoint_m[n()] + diff(layer_midpoint_m[c(n()-1, n() )])/2) *100,
         .by = study_name) %>%
  select(study_name,
          layer_top_cm, layer_bottom_cm, soil_organic_carbon) %>% 
  left_join(read_csv(file = 'data_lvl1/CPEAT_study.csv', 
                     col_types = cols(.default = col_character()))  %>%
              select(study_name = doi, core_name, latitude = LATITUDE, longitude = LONGITUDE,
                     location = LOCATION),
            by = 'study_name') # 15817 obs of 8 variables

all.df <- CPEAT.df %>% 
      select(profile_name = "study_name", site_name = "core_name", 
             "latitude", "longitude", "location",
             "layer_top_cm", "layer_bottom_cm", "soil_organic_carbon") %>%
      mutate(study_name = 'C-PEAT (2024)') %>%
      mutate(across(c(latitude, longitude), as.numeric)) %>%
      mutate(across(ends_with('_name'), as.character)) 


# Create the directory if it does not exist
if (!dir.exists("data_lvl2")) {
  dir.create("data_lvl2")
}
write_csv(all.df, file = 'data_lvl2/all_layer.csv')

```

```{r}
all.df <- read_csv('data_lvl2/all_layer.csv')

ggplot(all.df) +
  geom_histogram(aes(x=soil_organic_carbon)) +
  scale_x_log10()

ggplot(all.df) +
  geom_histogram(aes(x=layer_bottom_cm)) +
  scale_x_log10()

ggplot(all.df) + 
  geom_polygon(data = USMap, aes(x = long, y = lat, group = group), fill = NA, color = 'lightgrey') +
  geom_point(aes(x=longitude, y = latitude)) +
  labs(x = NULL, y = NULL)
```

```{r}
#common_grid <- sort(unique(c(all.df$layer_top_cm, all.df$layer_bottom_cm)))
common_grid <- seq(0, 1800, by = 1.5e-1)
common_mid <- c((common_grid[-1] + common_grid[-length(common_grid)])/2, Inf)

temp <- all.df %>%
  filter(is.finite(soil_organic_carbon) &
           is.finite(layer_bottom_cm)) %>%
  reframe(layer_mid = common_mid[common_mid < layer_bottom_cm & 
               common_mid > layer_top_cm], 
          .by = everything()) %>%
  #mutate(count = n(), .by = layer_mid)
  reframe(count = n(),
          soc_05 = quantile(soil_organic_carbon, 0.05),
          soc_33 = quantile(soil_organic_carbon, 0.33),
          soc_50 = quantile(soil_organic_carbon, 0.50),
          soc_66 = quantile(soil_organic_carbon, 0.66),
          soc_95 = quantile(soil_organic_carbon, 0.95),
          .by = c(layer_mid, study_name))

  
ggplot(temp) +
  geom_line(aes(x=layer_mid, y = count)) +
  scale_x_log10() +
  facet_wrap(~study_name, scales = 'free_y', ncol = 1)

ggplot(temp %>%
         filter(layer_mid < 101) %>%
         mutate(layer_mid = -layer_mid)) +
  geom_ribbon(aes(x=layer_mid, ymin = soc_05, ymax = soc_95), fill = 'red', alpha = 0.1) +
  geom_ribbon(aes(x=layer_mid, ymin = soc_33, ymax = soc_66), fill = 'red', alpha = 0.1) +
  geom_line(aes(x=layer_mid, y = soc_50)) +
  scale_y_log10() +
  coord_flip() +
  theme_bw() +
  facet_wrap(~study_name) +
  labs(x = 'Soil organic carbon [g/cm3]',
       y = 'Depth [cm]')
```

```{r}
common_grid <- seq(0, 1800, by = 1.5e-1)
common_mid <- c((common_grid[-1] + common_grid[-length(common_grid)])/2, Inf)

temp <- all.df %>%
  filter(is.finite(latitude + longitude)) %>%
  filter(layer_top_cm < 100) %>%
  mutate(layer_bottom_cm = if_else(layer_bottom_cm > 100, 100, layer_bottom_cm)) %>%
  filter(is.finite(soil_organic_carbon) &
           is.finite(layer_bottom_cm)) %>%
  reframe(layer_mid = common_mid[common_mid < layer_bottom_cm & 
               common_mid > layer_top_cm], 
          .by = everything()) %>%
  #round to the nearest 0.5 degree
  mutate(latitude_bin = round(latitude * 2) / 2,
         longitude_bin = round(longitude * 2)/ 2) %>%
  #mutate(count = n(), .by = layer_mid)
  reframe(count = n(),
          soc_05 = quantile(soil_organic_carbon, 0.05),
          soc_33 = quantile(soil_organic_carbon, 0.33),
          soc_50 = quantile(soil_organic_carbon, 0.50),
          soc_66 = quantile(soil_organic_carbon, 0.66),
          soc_95 = quantile(soil_organic_carbon, 0.95),
          .by = c(latitude_bin, longitude_bin, layer_mid))

# plotting SOC overlayed by their geo-locations at 50th percentile
USMap <- map_data('world')
ggplot(temp) +
  geom_polygon(data = USMap, aes(x = long, y = lat, group = group), fill = NA, color = 'lightgrey') +
  geom_point(aes(x=longitude_bin, y=latitude_bin, 
                color = soc_50)) +
  scale_color_viridis_b(name = 'Soil organic carbon (g/cm3)') +
  theme_bw() +
  labs(x = NULL, y = NULL)

ggplot(temp)+
  geom_polygon(data = USMap, aes(x = long, y = lat, group = group), fill = NA, color = 'lightgrey') +
  geom_tile(aes(x=longitude_bin, y=latitude_bin,
            fill = soc_50), width = 2.5, height = 2.5) +
  scale_fill_viridis_c(name = 'Soil organic carbon (g/cm3)') +
  theme_bw() +
  labs(x = NULL, y = NULL)
```

```{r}
# pulling out original CPEAT data with soil carbon covariates (without manual soc computation)
CPEAT <- read_csv(file = 'data_lvl1/CPEAT_layer.csv', #n_max = 3, 
                     col_types = cols(.default = col_character())) %>%
  select(study_name = doi, 
         contains('Depth sed'),
         #layer_top_m = 'Depth top [m]', layer_bottom_m = 'Depth bot [m]', #all NA
         organic_carbon = 'TOC [%]', carbon = "C [%]", 
         loss_on_ignition = "LOI [%] (weight-%)", 
         bulk_density = "DBD [g/cm**3]", 
         soil_organic_carbon = "Corg dens [g/cm**3]", soil_organic_matter = "OM dens [g/cm**3]" ) %>%
  dplyr::mutate(across(-study_name, as.numeric)) %>% 
  dplyr::mutate(layer_midpoint_m = case_when(is.finite(`Depth sed [m]`) ~ `Depth sed [m]`,
                                      is.finite(`Depth sed [m] (Sample midpoint depth)`) ~ `Depth sed [m] (Sample midpoint depth)`,
                                      is.finite(`Depth sed [m] (LOI sample depth)`) ~ `Depth sed [m] (LOI sample depth)`,
                                      TRUE ~ NA)) %>%
  select(-contains('Depth sed')) %>%
  left_join(read_csv(file = 'data_lvl1/CPEAT_study.csv', 
                     col_types = cols(.default = col_character()))  %>%
              select(study_name = doi, core_name, latitude = LATITUDE, longitude = LONGITUDE,
                     location = LOCATION),
            by = 'study_name') %>% 
  filter(!is.na(latitude) & !is.na(longitude) & !is.na(soil_organic_carbon))

```


```{r}
# plotting downcore organic carbon (OC) for CPEAT (no manual SOC computation)

ggplot(CPEAT) +
  geom_point(aes(y = layer_midpoint_m, x = soil_organic_carbon)) +
  scale_y_log10() +
  #coord_flip() +
  scale_y_reverse() +
  theme_bw() +
  #facet_wrap(~study_name) +
  labs(title = 'Down-core SOC against depth',
       y ='Soil organic carbon [g cm-3]',
       x = 'Depth [cm]')

# geolocations
ggplot(all.df) + 
  geom_polygon(data = USMap, aes(x = long, y = lat, group = group), fill = NA, color = 'lightgrey') +
  geom_point(aes(x=longitude, y = latitude)) +
  labs(title = 'C-PEAT geo-locations across the globe',
       x = NULL, y = NULL)

```

